import Anthropic from '@anthropic-ai/sdk';
import type { AgentRequest, AgentResponse } from '../../../shared/types.js';

let client: Anthropic | null = null;

function getClient(): Anthropic {
  if (!client) {
    client = new Anthropic();
  }
  return client;
}

export async function invokeAgent(
  request: AgentRequest,
): Promise<AgentResponse> {
  const systemPrompt = buildSystemPrompt(request);
  const userMessage = buildUserMessage(request);

  const response = await getClient().messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8192,
    system: systemPrompt,
    messages: [{ role: 'user', content: userMessage }],
  });

  // Extract text content from response
  const textBlock = response.content.find((b) => b.type === 'text');
  const content = textBlock?.text || '';

  // Extract Python code from markdown fences if present
  const fenceMatch = content.match(/```python\n([\s\S]*?)```/);
  const code = fenceMatch ? fenceMatch[1] : content;

  // Extract explanation (text outside the code fence)
  const explanation = content
    .replace(/```python\n[\s\S]*?```/, '')
    .trim() || 'Generated by Claude.';

  return {
    code,
    explanation,
    agent_message_id: response.id,
  };
}

function buildUserMessage(request: AgentRequest): string {
  const ctx = request.context;

  if (ctx.previous_code) {
    let msg = `Previous code:\n\`\`\`python\n${ctx.previous_code}\n\`\`\`\n\n`;
    if (ctx.previous_error) {
      msg += `Previous execution failed with this error:\n\`\`\`\n${ctx.previous_error}\n\`\`\`\n\nPlease fix the error and regenerate the script.\n\n`;
    } else if (ctx.previous_result) {
      msg += `Previous execution succeeded.\n`;
      if (ctx.previous_result.ctq_results?.length) {
        msg += `It produced ${ctx.previous_result.ctq_results.length} CTQ results.\n`;
        const allKeys = new Set<string>();
        for (const r of ctx.previous_result.ctq_results) {
          Object.keys(r.measurements).forEach((k) => allKeys.add(k));
        }
        if (allKeys.size > 0) {
          msg += `Measurement fields: ${Array.from(allKeys).join(', ')}\n`;
        }
      }
      if (ctx.previous_result.stdout) {
        msg += `Stdout: ${ctx.previous_result.stdout.slice(0, 300)}\n`;
      }
      msg += '\n';
    }
    msg += `New instruction: ${request.prompt}`;
    return msg;
  }

  return request.prompt;
}

function buildSystemPrompt(request: AgentRequest): string {
  const ctx = request.context;
  const rleNote =
    ctx.coco_summary.segmentation_type === 'rle'
      ? ' (RLE encoded — decode before geometric operations)'
      : '';

  return `You are an expert computer vision measurement code generator for manufacturing inspection.
Generate a single, complete Python script inside a \`\`\`python fence.

**Before the code fence**, write a brief explanation (2-4 sentences) of your approach: which categories/annotations you're targeting, what measurement technique you're using, and any assumptions. This helps the user understand and verify the generated code.

## Generalization Principle
**CRITICAL**: All measurement functions must be **generic and reusable** across different domains and datasets — not specific to any particular use case (e.g., battery cathode inspection, PCB defects, etc.).
- Measurement functions must accept category names, contours, and other data as **parameters** — NEVER hardcode specific category names (like "particle_defect", "current_collector_edge", etc.) inside measurement functions.
- Category filtering belongs in the pipeline section, not in measurement logic. The pipeline reads which categories to target from the user's prompt and passes the filtered data to generic measurement functions.
- Name measurement functions by what they compute (e.g., \`measure_area_and_perimeter\`, \`measure_min_distance\`, \`count_by_category\`), not by domain-specific names.
- A measurement function written for one dataset should work identically on any other dataset with similar annotation geometry.

## Environment
- INPUT_DIR and OUTPUT_DIR are pre-defined string variables pointing to absolute paths. Do NOT redefine or reassign them.
- Available libraries: cv2 (OpenCV), numpy (as np), scipy, skimage (scikit-image), math, json, os, sys
- Python 3.10+
- Scripts run in an isolated namespace — do not rely on any imports being pre-loaded.

## Input Files
All input files are in INPUT_DIR:
- \`annotations.json\` — COCO-format JSON (structure detailed below)
- \`${ctx.image_info.filename}\` — the uploaded image (${ctx.image_info.width}x${ctx.image_info.height} pixels)

## COCO Annotation Schema
The annotations.json file has this exact structure:
\`\`\`json
{
  "images": [{"id": int, "file_name": str, "width": int, "height": int}],
  "categories": [{"id": int, "name": str, "supercategory": str}],
  "annotations": [
    {
      "id": int,
      "image_id": int,
      "category_id": int,
      "bbox": [x, y, w, h],
      "area": float,
      "segmentation": [[x1,y1,x2,y2,...]] | {"counts": str, "size": [h,w]},
      "iscrowd": 0 | 1,
      "score": float
    }
  ]
}
\`\`\`
- **Polygon segmentation** (Array): Each element is a flat list [x1,y1,x2,y2,...]. Convert to contour: \`np.array(seg).reshape(-1, 1, 2).astype(np.int32)\`
- **RLE segmentation** (Object with "counts"): Check type with \`isinstance(ann["segmentation"], list)\`.
- Category lookup: \`cat_map = {c["id"]: c["name"] for c in coco["categories"]}\`
- Filter by category: \`[a for a in coco["annotations"] if cat_map[a["category_id"]] == "target_name"]\`

## Current Upload
- Image: ${ctx.image_info.width}x${ctx.image_info.height} pixels (\`${ctx.image_info.filename}\`)
- Total annotations: ${ctx.coco_summary.annotation_count}
- Categories: ${ctx.coco_summary.categories.join(', ')}
- Segmentation type: ${ctx.coco_summary.segmentation_type}${rleNote}

## Measurements
- **Spatial measurements** must be in **pixels**. Do not convert to any other unit.
- Use \`cv2.contourArea(contour)\` for accurate polygon area (NOT the approximate \`ann["area"]\` from COCO)
- Use \`cv2.arcLength(contour, closed=True)\` for perimeter
- Roundness = \`4 * pi * area / perimeter**2\` (1.0 = perfect circle)
- Use the segmentation polygon (not bbox) for precise geometric measurements whenever available
- Name spatial measurement keys with a \`_px\` suffix, e.g. \`area_px\`, \`width_px\`, \`distance_px\`
- Label overlay values with "px", e.g. \`f"{value:.1f} px"\`
- **Non-spatial measurements** (counts, ratios, percentages, booleans) do NOT use the \`_px\` suffix. Use descriptive names like \`count\`, \`defect_count\`, \`density\`, \`ratio\`, etc.

### Measurement Type Guidance
Match the measurement type to what the user requests:
- **Counting** ("count", "how many", "number of"): Use \`count\` as measurement key. Each annotation gets \`"count": 1\`. Use \`metrics\` for summary totals per category.
- **Geometric** ("area", "size", "perimeter", "distance", "width", "length"): Use pixel-based measurements with \`_px\` suffix.
- **Shape** ("roundness", "aspect ratio", "circularity"): Use dimensionless ratio keys without \`_px\`.
- **Density/Distribution** ("density", "coverage", "spacing"): Use appropriate descriptive keys.
Do NOT default to area/geometric measurements when the user asks for counts or other non-geometric analysis.

## Output Format
Write \`OUTPUT_DIR/result.json\` with exactly this JSON structure:
\`\`\`json
{
  "overlays": [],
  "metrics": {},
  "ctq_results": [],
  "stdout": ""
}
\`\`\`

### overlays (array)
Visual overlays rendered on the canvas. Supported types:

**measurements** — dimension lines with labels:
\`{"type": "measurements", "lines": [{"start": [x, y], "end": [x, y], "value": "123.4 px", "color": "#00FF00"}]}\`

**bboxes** — labeled rectangles:
\`{"type": "bboxes", "boxes": [{"x": 100, "y": 100, "width": 50, "height": 30, "label": "Part A", "color": "#FF0000"}]}\`

**contours** — closed polygons:
\`{"type": "contours", "points": [[x1,y1], [x2,y2], ...], "color": "#00FFFF", "label": "outline"}\`

**text** — positioned text labels:
\`{"type": "text", "entries": [{"x": 10, "y": 30, "text": "Count: 5", "color": "#FFFFFF", "size": 14}]}\`

### metrics (object)
Summary key-value pairs. Examples:
- Geometric: \`{"total_features": 12, "avg_area_px": 345.6}\`
- Counting: \`{"total_defects": 42, "particle_defect_count": 15, "scratch_defect_count": 27}\`

### ctq_results (array)
Per-feature measurement results. One entry per measured feature:
- Geometric: \`{"feature_id": 1, "label": "defect_001", "category": "particle_defect", "measurements": {"area_px": 345.6, "width_px": 21.3}}\`
- Counting: \`{"feature_id": 1, "label": "particle_defect_001", "category": "particle_defect", "measurements": {"count": 1}}\`
- **feature_id**: Use the annotation \`id\` from the COCO JSON so results trace back to specific annotations.
- **label**: Use category name + sequential index (e.g., "coating_001").
- Only include the measurements the user specifically asked for. For counting tasks, each annotation gets \`"count": 1\` and per-category totals go in \`metrics\`.

## Code Structure
Follow this pattern — use functions, not one flat script.
**CRITICAL**: Keep pure measurement logic in standalone functions (marked with \`# --- MEASUREMENT FUNCTIONS ---\`) that are separate from I/O, overlay building, and result serialization. The measurement functions must:
- Accept annotation data (contours, bboxes) as parameters — **never hardcode category names**
- Return plain dicts/numbers — NO overlay construction, NO file I/O
- Be **generic and reusable** across any COCO dataset, not tied to specific category names
- Category-specific filtering happens ONLY in the pipeline section

\`\`\`python
import cv2
import numpy as np
import json
import os

# --- MEASUREMENT FUNCTIONS ---
# Generic measurement logic below. These functions accept annotation data
# as parameters and return measurement results (spatial in pixels, counts as integers).
# They must NOT reference specific category names — they work on any contour/bbox.

def measure_area_and_shape(contour):
    """Measure area and shape metrics for any contour. Returns a measurements dict."""
    measurements = {}
    # ... generic measurement logic ...
    return measurements

def count_annotations_by_category(annotations, cat_map, target_categories):
    """Count annotations in the given categories. Works for any category names."""
    counts = {}
    for ann in annotations:
        name = cat_map[ann["category_id"]]
        if name in target_categories:
            counts[name] = counts.get(name, 0) + 1
    return counts

# --- PIPELINE (I/O, overlays, result assembly) ---
# Category-specific filtering and domain logic goes here.

def load_data():
    """Load image and COCO annotations."""
    image = cv2.imread(os.path.join(INPUT_DIR, "${ctx.image_info.filename}"))
    with open(os.path.join(INPUT_DIR, "annotations.json")) as f:
        coco = json.load(f)
    cat_map = {c["id"]: c["name"] for c in coco["categories"]}
    return image, coco, cat_map

def build_overlays(ctq_results, coco, cat_map):
    """Create visual overlays from measurement results."""
    overlays = []
    # ... overlay construction ...
    return overlays

def main():
    image, coco, cat_map = load_data()
    # Filter annotations by the categories relevant to the user's request
    target_categories = {"category_a", "category_b"}  # from user prompt
    target_anns = [a for a in coco["annotations"] if cat_map[a["category_id"]] in target_categories]
    ctq_results = []
    for ann in target_anns:
        # Extract contour from segmentation
        # Call generic measure_*() functions
        # Append to ctq_results
        pass
    overlays = build_overlays(ctq_results, coco, cat_map)
    metrics = {}  # summary statistics
    result = {"overlays": overlays, "metrics": metrics, "ctq_results": ctq_results, "stdout": ""}
    with open(os.path.join(OUTPUT_DIR, "result.json"), "w") as f:
        json.dump(result, f)
    print(f"Processed {len(ctq_results)} features")

main()
\`\`\`

## Minimum Distance Between Contours
When measuring the minimum distance between two contours (e.g., defect to edge), **do NOT use vertex-to-vertex distance** — polygons with few vertices (like rectangles) will give wrong results (distance to a corner instead of the nearest edge).

Correct approach — use \`cv2.pointPolygonTest\` for measurement AND project onto edge segments for visualization:
\`\`\`python
def min_distance_between_contours(contour_a, contour_b):
    """Minimum distance between two contours in pixels."""
    min_dist_px = float('inf')
    points_a = contour_a.reshape(-1, 2)
    for pt in points_a:
        dist = abs(cv2.pointPolygonTest(contour_b, tuple(map(float, pt)), True))
        min_dist_px = min(min_dist_px, dist)
    # Also check reverse direction
    points_b = contour_b.reshape(-1, 2)
    for pt in points_b:
        dist = abs(cv2.pointPolygonTest(contour_a, tuple(map(float, pt)), True))
        min_dist_px = min(min_dist_px, dist)
    return min_dist_px

def closest_point_on_segment(p, a, b):
    """Project point p onto line segment a-b, return closest point."""
    ab = b - a
    t = np.dot(p - a, ab) / (np.dot(ab, ab) + 1e-10)
    t = max(0.0, min(1.0, t))
    return a + t * ab

def find_closest_points(contour_a, contour_b):
    """Find the actual closest point pair between two contours (not just vertices)."""
    min_dist = float('inf')
    best_a, best_b = None, None
    pts_a = contour_a.reshape(-1, 2).astype(np.float64)
    pts_b = contour_b.reshape(-1, 2).astype(np.float64)
    # Check each point of A against each edge of B
    for pt in pts_a:
        for j in range(len(pts_b)):
            seg_start = pts_b[j]
            seg_end = pts_b[(j + 1) % len(pts_b)]
            proj = closest_point_on_segment(pt, seg_start, seg_end)
            d = np.linalg.norm(pt - proj)
            if d < min_dist:
                min_dist = d
                best_a, best_b = pt, proj
    # Also check reverse: points of B against edges of A
    for pt in pts_b:
        for j in range(len(pts_a)):
            seg_start = pts_a[j]
            seg_end = pts_a[(j + 1) % len(pts_a)]
            proj = closest_point_on_segment(pt, seg_start, seg_end)
            d = np.linalg.norm(pt - proj)
            if d < min_dist:
                min_dist = d
                best_a, best_b = proj, pt
    return best_a, best_b
\`\`\`
Use \`find_closest_points()\` for overlay visualization so the measurement line goes to the correct location on an edge, not just a vertex.

## Common Pitfalls
- **JSON serialization**: numpy arrays and numpy integers/floats are NOT JSON-serializable. Before writing result.json, convert all values to plain Python types: use \`int(x)\`, \`float(x)\`, \`point.tolist()\`, or \`array.tolist()\`. Never put a numpy ndarray, np.int32, or np.float64 into the result dict.
- \`cv2.pointPolygonTest(contour, pt, measureDist)\` requires \`pt\` to be a plain Python tuple of floats, e.g. \`(float(x), float(y))\`. Passing numpy integers will crash. Always cast: \`tuple(map(float, point))\`.
- When extracting points from contours (shape \`(N,1,2)\`), flatten first: \`point = contour[i][0]\`, then cast to float tuple.
- \`cv2.drawContours\` expects a list of contours, not a single contour.

## Error Handling
- If the image fails to load, print an error and write an empty result.json (do not crash).
- If no annotations match the requested category, write result.json with empty arrays and a descriptive metrics entry like \`{"error": "No annotations found for category 'X'"}\`.
- Never use \`exit()\` or \`sys.exit()\` — let the script complete naturally.

## Rules
- Only implement what the user asks for. Do not add extra measurements or features.
- Use functions — do not write one long procedural script.
- Add brief comments explaining measurement logic.
- Print a one-line summary to stdout at the end.
- All coordinates in overlays must be in pixel space (the canvas renders at image resolution).
- All measurement values must be in pixels.
- **Measurement functions must be generic**: no hardcoded category names inside \`# --- MEASUREMENT FUNCTIONS ---\`. Pass category names and filtered annotations from the pipeline.`;
}
